//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUM.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUM.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string str_add {
            get {
                return ResourceManager.GetString("str_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want delete this backup.
        /// </summary>
        internal static string str_ask_del_bu {
            get {
                return ResourceManager.GetString("str_ask_del_bu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want delete this game from list?\nThe backups are not going be deleted.
        /// </summary>
        internal static string str_ask_del_game {
            get {
                return ResourceManager.GetString("str_ask_del_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want restore this backup?\nyour current save is going overwrite..
        /// </summary>
        internal static string str_ask_load_save {
            get {
                return ResourceManager.GetString("str_ask_load_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atention.
        /// </summary>
        internal static string str_atention {
            get {
                return ResourceManager.GetString("str_atention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Backup.
        /// </summary>
        internal static string str_backup {
            get {
                return ResourceManager.GetString("str_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game.
        /// </summary>
        internal static string str_col_juegos {
            get {
                return ResourceManager.GetString("str_col_juegos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saves path.
        /// </summary>
        internal static string str_col_path_saves {
            get {
                return ResourceManager.GetString("str_col_path_saves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string str_delete {
            get {
                return ResourceManager.GetString("str_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The game name can&apos;t be on blank..
        /// </summary>
        internal static string str_err_blank_game {
            get {
                return ResourceManager.GetString("str_err_blank_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The name of backup can&apos;t be on blank.
        /// </summary>
        internal static string str_err_blank_save {
            get {
                return ResourceManager.GetString("str_err_blank_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string str_error {
            get {
                return ResourceManager.GetString("str_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chose a game first.
        /// </summary>
        internal static string str_melon {
            get {
                return ResourceManager.GetString("str_melon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open folder.
        /// </summary>
        internal static string str_open_folder {
            get {
                return ResourceManager.GetString("str_open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore.
        /// </summary>
        internal static string str_restore {
            get {
                return ResourceManager.GetString("str_restore", resourceCulture);
            }
        }
    }
}
